# Generated by Django 4.1.7 on 2023-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
