# Generated by Django 4.1.7 on 2023-03-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_image_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_deleted',
        ),
    ]
